# Generated by Django 2.2 on 2019-10-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacciapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FibonacciTest',
            new_name='Fibonacci',
        ),
    ]
