# Generated by Django 2.2 on 2019-10-07 16:05

from django.ab import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacciapp', '0002_auto_20191007_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibonacci',
            old_name='numeric',
            new_name='number',
        ),
    ]
